-- Claudia Benassuly CMS — source defaults seed
-- Generated from lib/cms-defaults.ts. No passwords or sessions included.
begin;

insert into public.cms_content (key, value, updated_at) values ('heroEyebrow', 'Uma nova voz para o Pará', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('heroTitle', 'Política que', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('heroTitleEm', 'escuta.', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('heroSubline', 'Trabalho que transforma.', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('proposalsJson', '[{"number":"01","title":"Autonomia econômica","copy":"Creches, crédito, inclusão digital e oportunidades para que cada mulher possa escolher o próprio caminho.","tag":"Trabalho & renda","icon":"bank"},{"number":"02","title":"Segurança e justiça","copy":"Mais orçamento para proteger mulheres, combater a violência e fazer a justiça chegar mais rápido.","tag":"Proteção real","icon":"scales"},{"number":"03","title":"Saúde integral","copy":"Prevenção, atendimento humanizado, saúde mental e cuidado para todas as fases da vida.","tag":"SUS que acolhe","icon":"health"},{"number":"04","title":"Participação e inclusão","copy":"A política precisa refletir a vida de mulheres periféricas, negras, indígenas, ribeirinhas e rurais.","tag":"Voz & presença","icon":"community"}]', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('heroLede', 'Cláudia Benassuly coloca seu nome à disposição para levar a voz das mulheres da vida real ao Congresso Nacional.', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('slogan', 'Por ela. Por nós. Por todas.', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('manifestoWords', 'escuta · coragem · presença · futuro', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('storyEyebrow', 'A história por trás do nome', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('storyTitle', 'Quem conhece a realidade,', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('storyTitleEm', 'sabe onde agir.', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('storyLead', 'A mulher brasileira acorda antes do sol, cuida, trabalha, empreende e resolve. Mas as decisões que mudam a sua vida ainda são tomadas sem a sua voz.', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('storyBody', 'Cláudia chega para mudar essa lógica. Sua candidatura nasce da escuta, do compromisso com as mulheres e da certeza de que política só faz sentido quando melhora a vida de quem está na ponta.', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('quote', 'Esta candidatura não é minha.', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('quoteEm', 'Ela é nossa.', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('quoteDescription', 'Uma mulher na política muda a sua história. Muitas mulheres na política mudam a história do país.', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('santinhoEyebrow', 'Leve a mensagem com você', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('santinhoTitle', 'O santinho agora é', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('santinhoTitleEm', 'digital.', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('santinhoDescription', 'Compartilhe a história, as propostas e o número 2323 da Cláudia com quem precisa conhecer uma nova voz para o Pará.', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('santinhoKicker', 'Por ela. Por nós. Por todas.', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('santinhoBody', 'Uma nova voz para o Pará, com escuta, presença e compromisso com as mulheres da vida real.', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('santinhoMessageTitle', 'Presença que cuida.', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('santinhoMessageBody', 'Conheça as propostas e participe da construção desse projeto.', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('joinTitle', 'Uma campanha forte começa quando', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('joinTitleEm', 'você chega junto.', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('joinDescription', 'Receba notícias, agenda e formas de participar da construção desse projeto.', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('candidateNumber', '2323', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('partyName', 'Cidadania', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('topRibbonLabel', 'Candidata a Deputada Federal', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('heroPartyCaption', 'número 23 · candidata 2323', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('heroNumberLabel', 'Deputada Federal · Cidadania', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('signupRecipientEmail', 'draclaudiabenassuly@gmail.com', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('coalitionName', 'O PARÁ TÁ JUNTO', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('coalitionParties', 'MDB · Federação UNIÃO BRASIL-PP · Federação PT-PCdoB-PV · Federação PSDB-Cidadania · PSD · PSB · REPUBLICANOS · AVANTE', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('coalitionGovernorName', 'Hanna', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('coalitionGovernorNumber', '15', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('coalitionSenatorName', 'Helder', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('coalitionSenatorNumber', '151', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('coalitionStateDeputyName', 'Antônia Brito', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('coalitionStateDeputyNumber', '23222', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('coalitionFederalDeputyName', 'Cláudia Benassuly', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('coalitionFederalDeputyNumber', '2323', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('siteHeaderLogo', '/campaign/logo-transparent-color.png', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('siteFooterLogo', '/campaign/logo-transparent-footer.png', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('digitalCardLogo', '/campaign/logo-transparent-dark.png', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('santinhoLogo', '/campaign/logo-name-white.png', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('partyLightLogo', '/campaign/cidadania-logo-compact.png', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('partyDarkLogo', '/campaign/cidadania-logo-footer.png', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('ogImage', '/og.png', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('heroImage', '/campaign/claudia-portrait-clean.jpg', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('storyImage', '/campaign/claudia-hero.jpeg', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('santinhoImage', '/campaign/claudia-hero.jpeg', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('galleryImage1', '/campaign/gallery-principal.jpg', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('galleryImage2', '/campaign/gallery-identidade.png', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('galleryImage3', '/campaign/gallery-saude.png', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('galleryImage4', '/campaign/gallery-justica.png', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;
insert into public.cms_content (key, value, updated_at) values ('galleryImage5', '/campaign/gallery-autonomia.png', now()) on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at;

insert into public.agenda_events (id, date, day, month, title, location, detail, tone, sort_order, updated_at) values ('escuta-mulheres-empreendedoras', '22 ago 2026', '22', 'AGO', 'Escuta com mulheres empreendedoras', 'Ananindeua · Pará', 'Roda de conversa sobre crédito, autonomia e oportunidades para quem empreende.', 'teal', 0, now()) on conflict (id) do update set date = excluded.date, day = excluded.day, month = excluded.month, title = excluded.title, location = excluded.location, detail = excluded.detail, tone = excluded.tone, sort_order = excluded.sort_order, updated_at = excluded.updated_at;
insert into public.agenda_events (id, date, day, month, title, location, detail, tone, sort_order, updated_at) values ('liderancas-femininas', '29 ago 2026', '29', 'AGO', 'Encontro de lideranças femininas', 'Belém · Pará', 'Uma conversa aberta sobre segurança, participação política e futuro.', 'blue', 1, now()) on conflict (id) do update set date = excluded.date, day = excluded.day, month = excluded.month, title = excluded.title, location = excluded.location, detail = excluded.detail, tone = excluded.tone, sort_order = excluded.sort_order, updated_at = excluded.updated_at;
insert into public.agenda_events (id, date, day, month, title, location, detail, tone, sort_order, updated_at) values ('cafe-comunidade', '05 set 2026', '05', 'SET', 'Café com a comunidade', 'Região Metropolitana de Belém', 'A campanha vai até as pessoas para ouvir o que realmente precisa mudar.', 'gold', 2, now()) on conflict (id) do update set date = excluded.date, day = excluded.day, month = excluded.month, title = excluded.title, location = excluded.location, detail = excluded.detail, tone = excluded.tone, sort_order = excluded.sort_order, updated_at = excluded.updated_at;

insert into public.news_posts (id, category, title, excerpt, read_time, image, published_at, sort_order, updated_at) values ('creche-tempo-integral', 'Autonomia econômica', 'Creche em tempo integral também é liberdade para trabalhar', 'Quando uma mãe tem onde deixar seu filho com segurança, ela ganha tempo, renda e tranquilidade para construir seus planos.', '4 min de leitura', '/campaign/gallery-autonomia.png', '2026-08-01', 0, now()) on conflict (id) do update set category = excluded.category, title = excluded.title, excerpt = excluded.excerpt, read_time = excluded.read_time, image = excluded.image, published_at = excluded.published_at, sort_order = excluded.sort_order, updated_at = excluded.updated_at;
insert into public.news_posts (id, category, title, excerpt, read_time, image, published_at, sort_order, updated_at) values ('pensao-alimenticia', 'Segurança e justiça', 'Pensão alimentícia no bolso, sem enrolação', 'A defesa de mecanismos mais rápidos e digitais para garantir o direito de crianças e mães precisa sair do discurso.', '3 min de leitura', '/campaign/gallery-justica.png', '2026-08-04', 1, now()) on conflict (id) do update set category = excluded.category, title = excluded.title, excerpt = excluded.excerpt, read_time = excluded.read_time, image = excluded.image, published_at = excluded.published_at, sort_order = excluded.sort_order, updated_at = excluded.updated_at;
insert into public.news_posts (id, category, title, excerpt, read_time, image, published_at, sort_order, updated_at) values ('saude-da-mulher', 'Saúde da mulher', 'Exame preventivo não pode esperar meses', 'A saúde da mulher merece prevenção, diagnóstico rápido e acolhimento em todas as fases da vida.', '5 min de leitura', '/campaign/gallery-saude.png', '2026-08-07', 2, now()) on conflict (id) do update set category = excluded.category, title = excluded.title, excerpt = excluded.excerpt, read_time = excluded.read_time, image = excluded.image, published_at = excluded.published_at, sort_order = excluded.sort_order, updated_at = excluded.updated_at;

insert into public.gallery_albums (id, title, slug, description, cover, published_at, featured, sort_order, updated_at) values ('campanha-2026', 'Campanha 2026', 'campanha-2026', 'Identidade, propostas e registros da caminhada de Cláudia Benassuly.', '/campaign/gallery-principal.jpg', '2026-08-24', true, 0, now()) on conflict (id) do update set title = excluded.title, slug = excluded.slug, description = excluded.description, cover = excluded.cover, published_at = excluded.published_at, featured = excluded.featured, sort_order = excluded.sort_order, updated_at = excluded.updated_at;
insert into public.gallery_photos (id, album_id, title, caption, image, alt, published_at, featured_on_home, sort_order, updated_at) values ('galeria-principal', 'campanha-2026', 'Registro principal', 'Por ela. Por nós. Por todas.', '/campaign/gallery-principal.jpg', 'Registro principal da campanha', '2026-08-24', true, 0, now()) on conflict (id) do update set title = excluded.title, caption = excluded.caption, image = excluded.image, alt = excluded.alt, published_at = excluded.published_at, featured_on_home = excluded.featured_on_home, sort_order = excluded.sort_order, updated_at = excluded.updated_at;
insert into public.gallery_photos (id, album_id, title, caption, image, alt, published_at, featured_on_home, sort_order, updated_at) values ('galeria-identidade', 'campanha-2026', 'Identidade visual', 'A presença que identifica esta candidatura.', '/campaign/gallery-identidade.png', 'Identidade visual da campanha', '2026-08-24', true, 1, now()) on conflict (id) do update set title = excluded.title, caption = excluded.caption, image = excluded.image, alt = excluded.alt, published_at = excluded.published_at, featured_on_home = excluded.featured_on_home, sort_order = excluded.sort_order, updated_at = excluded.updated_at;
insert into public.gallery_photos (id, album_id, title, caption, image, alt, published_at, featured_on_home, sort_order, updated_at) values ('galeria-saude', 'campanha-2026', 'Saúde da mulher', 'Exame preventivo não pode esperar meses.', '/campaign/gallery-saude.png', 'Arte da campanha sobre saúde da mulher', '2026-08-24', true, 2, now()) on conflict (id) do update set title = excluded.title, caption = excluded.caption, image = excluded.image, alt = excluded.alt, published_at = excluded.published_at, featured_on_home = excluded.featured_on_home, sort_order = excluded.sort_order, updated_at = excluded.updated_at;
insert into public.gallery_photos (id, album_id, title, caption, image, alt, published_at, featured_on_home, sort_order, updated_at) values ('galeria-justica', 'campanha-2026', 'Segurança e justiça', 'Pensão alimentícia no bolso, sem enrolação.', '/campaign/gallery-justica.png', 'Arte da campanha sobre segurança e justiça', '2026-08-24', true, 3, now()) on conflict (id) do update set title = excluded.title, caption = excluded.caption, image = excluded.image, alt = excluded.alt, published_at = excluded.published_at, featured_on_home = excluded.featured_on_home, sort_order = excluded.sort_order, updated_at = excluded.updated_at;
insert into public.gallery_photos (id, album_id, title, caption, image, alt, published_at, featured_on_home, sort_order, updated_at) values ('galeria-autonomia', 'campanha-2026', 'Autonomia econômica', 'Creche em tempo integral também é liberdade para trabalhar.', '/campaign/gallery-autonomia.png', 'Arte da campanha sobre autonomia econômica', '2026-08-24', true, 4, now()) on conflict (id) do update set title = excluded.title, caption = excluded.caption, image = excluded.image, alt = excluded.alt, published_at = excluded.published_at, featured_on_home = excluded.featured_on_home, sort_order = excluded.sort_order, updated_at = excluded.updated_at;

commit;
